###
POST http://10.33.0.66:3002/login
Content-Type: application/json

{ "username": "username" }


###
GET http://fauques.freeboxos.fr:3000/matches
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJlMzE3MjExMy1jNzgyLTRmZGItOTEwZC0yMDgzZTNiOGMyODYiLCJ1c2VybmFtZSI6InZnZHMiLCJpYXQiOjE2Mzg4NzY0MzAsImV4cCI6MTY3MDQzNDAzMH0.uh6YTzeCtS6DsjfuwNp7d6dxAuF72lsY5NfqCteAY8w


###
GET http://fauques.freeboxos.fr:3000/matches/61af511f05be72d00a5ce386
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJlMzE3MjExMy1jNzgyLTRmZGItOTEwZC0yMDgzZTNiOGMyODYiLCJ1c2VybmFtZSI6InZnZHMiLCJpYXQiOjE2Mzg4NzY0MzAsImV4cCI6MTY3MDQzNDAzMH0.uh6YTzeCtS6DsjfuwNp7d6dxAuF72lsY5NfqCteAY8w
